### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by thistehneisen** [xxhomey19/nba-go#16] opened 2017-11-07 20:19 UTC
```
‹master*› »»»» nba-go game -d 2017/11/07                                                                                                    0|22:18:10
/usr/local/lib/node_modules/nba-go/node_modules/nba/src/team-info.js:28
  ]).then(function ([teamStats, teamYears]) {
                    ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nba-go/node_modules/nba/src/index.js:1:84)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
[~/homestead|2.7.13]
‹master*› »»»» nba-go game -y                                                                                                               1|22:18:34
/usr/local/lib/node_modules/nba-go/node_modules/nba/src/team-info.js:28
  ]).then(function ([teamStats, teamYears]) {
                    ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nba-go/node_modules/nba/src/index.js:1:84)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
[~/homestead|2.7.13]

```

**Comment by emyarod** [comment] 2017-11-07 23:23
I am unable to replicate this issue. Which version of node are you using?

**Comment by ravendark** [comment] 2017-11-08 01:02
im getting the same thing, nodejs is 4.2.6 from ubuntu 16.04 repo

**Comment by emyarod** [comment] 2017-11-08 02:53
yeah I think it has to do with older node versions not being able to do destructuring assignment, but I could be wrong

**Comment by kevinkaske** [comment] 2017-11-08 03:46
I'm also seeing this issue. I'm on Node v5.1.1 on MacOS 10.11.

**Comment by kevinkaske** [comment] 2017-11-08 03:50
Upgrading node to v6.11.3 seems to have fixed the issue.

**Comment by xxhomey19** [comment] 2017-11-08 03:52
Hi all,
I build this project by [Babel](https://babeljs.io/) and configure `babel-preset-env` for node version 6.0.0 in [.babelrc](https://github.com/xxhomey19/nba-go/blob/master/.babelrc).  
So, upgrading node version above 6.0.0 should fix  this issue.

**Comment by emyarod** [comment] 2017-11-08 04:28
Thanks for confirming @xxhomey19. Just curious, how come you are targeting Node version 6? Isn't `babel-preset-env` capable of transpiling down to support any node version?

**Comment by xxhomey19** [comment] 2017-11-08 06:52
According to https://github.com/nodejs/Release#lts_schedule
Node v4.X will not be maintained after April 2018. Therefore, I think using v6 is better.

It seems like the problem is resolved. Close this issue.

**Closed by xxhomey19** 2017-11-08 06:52 UTC
