### ISSUE TITLE
Fix timezone problem

### ISSUE THREAD

**Issue by xxhomey19** [xxhomey19/nba-go#2] opened 2017-11-06 05:49 UTC

**Comment by cagross** [comment] 2017-11-06 13:42
Hey I saw this on Reddit, and it looks like a fun project.  I'm an NBA fan and have been looking for an open source project I can contribute to.  But I'm looking for something that requires JavaScript or PHP (or CSS/HTML, but I don't think your project utilizes those).  Would this particular issue/project require either of those?  Perhaps JS, as I see a JS file in your repo?

**Comment by xxhomey19** [comment] 2017-11-06 14:03
Hi @cagross,
Yes, I believe this issue should be resolved by some kinds of npm package, which means it will be built by JS. This project is also built by JS, and I think it won't need CSS or HTML at this moment.

**Comment by cagross** [comment] 2017-11-06 14:23
OK cool.  I tried to get started with the [Getting Started tutorial](https://www.npmjs.com/package/nba-go/tutorial).  I managed to install Node on my computer (Win 10, x64), and I also installed the nba-go package (I can confirm there is an 'nba-go' directory in /node_modules/). But when I try to run any command, I encounter a “command not found" error.  Thoughts on what I'm doing wrong?  I encounter the issue no matter what directory 

FYI I installed Node via https://nodejs.org/download/release/latest/node-v9.0.0-x64.msi.

**Comment by xxhomey19** [comment] 2017-11-06 14:58
Hi, well, I haven't used Windows computer for few years, so I don't know how to resolve it exactly.
Maybe you can google something like "Windows npm install global command not found".
There will have some warnings when you installed it, and it's fine. It may caused by some dependencies, but it won't make this CLI crash. So, just leave it.

**Comment by cagross** [comment] 2017-11-06 15:35
OK I got it working.  I Googled your suggestion and found [this post](https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows) which indicates I need to ensure the Node binaries are in a directory specified by my PATH.  I had no idea how to edit my path, but then found [this page](http://www.chambaud.com/2013/07/08/adding-git-to-path-when-using-github-for-windows/) which got me most of the way there.  Using those instructions, I added the path C:\Users\<user>l\AppData\Roaming\npm to my environmental variables.  After, the nba-go commands began to work as expected.

OK so on to the issue.  First of all, I'm not entirely clear why you would want to get the user's local time zone.  I've tested some of the features, and don't see where knowing the user's local time zone would be necessary/beneficial.  I'm not arguing with you--I just want to make sure I'm misunderstanding the program correctly.

More importantly, if I was to to add the user's local time zone, in what file(s) would I do so?

**Comment by xxhomey19** [comment] 2017-11-06 16:12
Cool!
Sorry about that the title of this issue is not precise enough. Why I opened this issue is I found that I have to enter `nba-go game -y` to get "today's" game schedule. That is because I'm in Asia. My timezone is UTC +8 which is much different from ET timezone. Therefore, I hope this issue could fix this problem. No matter which timezone users lives in, when they enter `nba-go game -t`, they should get **today (their today) 's** game schedule.

I think additional code should be added around here.
https://github.com/xxhomey19/nba-go/blob/725609b99fd93bcf05638b29b0f72bf35ac981ec/src/command/game/index.js#L47-L65

**Comment by cagross** [comment] 2017-11-06 18:10
OK I see your issue.  Couldn't we resolve the issue by obtaining current UTC (using `Date().getTime()`), instead of grabbing the user's time zone?  If we grab UTC, then we can calculate current US east coast day/time.  Then we can use the US east coast day/time to fetch the requested schedule.  Does that make sense?  Let me try to explain further.

What I am proposing is essentially what nba.com does with their scores page ([link here](https://watch.nba.com/game/20171105/ATLCLE?ls=iref%3Anba%3Agnav&left=true).  Opening this link on nba.com is equivalent to running `nba-go game -t` in your program.  What this nba.com page does, logically, is the following: 
 
- The page checks the current eastern US time.
- If the current eastern US time is after 12:00 PM, the page displays the pregame matchups for the coming evening games.
- As games start, the page will display in-progress updates for those games.  As games complete, the page will display final scores for those games.  The page will continue to display these final scores until 12:00 PM (eastern time) the next day, at which point the cycle will begin anew.

Would you be OK if I implemented a similar solution?  If so, I think I could do so without obtaining the user's current time zone--I think all I would need is the current UTC time.  Would you agree with that?

FYI, the the logic followed by nba.com might change occasionally.  For example, sometimes nba.com might bump up the 12:00 PM changeover time by a few hours, on days that have early games.  Christmas Day might have four games of basketball, with the first starting at 12:00 PM eastern time.  The same is true on Saturdays and Sundays throughout the season.  On those days, nba.com might change the rollover time from 12:00 pm to 7:00 am (eastern time).  I'm not sure if your program would need to worry about such changes (probably not).  But if you want to account for this, I could add in a feature that automatically checks the start time of tomorrow's games.  If there is an early start time, then I could ensure the rollover time is automatically modified accordingly.  Maybe we can discuss this after I've made the first edit.

I hope that all made sense.  Let me know what you think.  I'm of course open to discuss.

**Comment by xxhomey19** [comment] 2017-11-07 01:19
Yes! This solution should work.
Just do your best and send a pull request to this repo. I'll check it out at that moment!
Thanks for all your help.

**Comment by cagross** [comment] 2017-11-08 16:44
OK I'm back.  Sorry, real world work called.

I'm really keen on contributing to this project.  But I'm having difficulty starting.  Specifically, I have forked your repo, saved the files to my local computer, and installed node.js for Windows on my computer.  But I can't figure out how to run the program from the files I just downloaded.  When I try the command 'nba-go,' I encounter `bash: nba-go: command not found`.  I'm not sure how to proceed.  Any ideas?

If not, I guess I could try posting for help on some node forums.

**Comment by aselamal** [comment] 2017-11-09 02:41
@cagross @xxhomey19 With the today flag `-t` time is already generated correctly using `Date.now()` This is already an UTC based value (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now)

The problem seems to come from the library [Nba stats client](https://github.com/jaebradley/nba-client/blob/master/src/NbaStatsClient.js) and how it uses moment.js to format a date for the url.

**Comment by xxhomey19** [comment] 2017-11-09 03:01
Hi @cagross ,
I have add development instruction is README. Try it out.

Hi @cagross ,
definitely, moment.js should be able to fix this problem!

**Comment by cagross** [comment] 2017-11-11 10:38
Hi @xxhomey19,

>> I have add development instruction is README. Try it out.

Which instructions are you referring to?  I see in the README there is a new section, "Development."  It has the commands:

```
$ git clone https://github.com/xxhomey19/nba-go.git
$ cd nba-go
$ yarn
$ NODE_ENV=development node bin/cli.js <command>
```
I tried those instructions. But when I entered `yarn` I encountered the usual error `bash: yarn: command not found`.  Thoughts?  

I want to say the issue is related to the fact that my command line application (Git Bash) isn't looking in the correct directory when attempting to execute commands.  I've seen other posts from people with the same issue.  But I can't be sure, because when I try the fixes proposed in those posts, they don't seem to work.

>> definitely, moment.js should be able to fix this problem!

I didn't see anything about moment.js in the README file.  Did I miss it?

Thanks!

**Comment by xxhomey19** [comment] 2017-11-11 14:31
@cagross 
yarn: https://yarnpkg.com/en/
Moment.js: https://momentjs.com/timezone/

**Comment by cagross** [comment] 2017-11-11 14:44
OK.  I installed Yarn, and tried your four 'Development' instructions.  Steps 1 and 2 completed without issue.   Step 3 completed with the following output:

```
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > babel-jest@21.2.0" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0".
[5/5] Building fresh packages...
Done in 24.50s.

```
But I am having an issue with Step 4.  I tried:

`$ NODE_ENV=development node bin/cli.js nba-go player Curry -p`

but was met with:

`Unknown command: nba-go`

Thoughts?

**Comment by xxhomey19** [comment] 2017-11-11 15:18
No, you shouldn't enter nba-go.
Just enter 
```
$ NODE_ENV=development node bin/cli.js player Curry -p
``` 

You should read more source code then you will understand.

**Comment by cagross** [comment] 2017-11-11 17:28
OK, that worked.  Thanks very much for being patient.

I've worked on the issue, and made a small change that I think should resolve it.

But before I get to that, it looks like I'm encountering a separate issue.  It looks like there is an offset between when scores appear on nba.com, and when scores appear in nba-go.  To clarify, it is now 12:15 AM on 12 November in Thailand.  If I look at today's scores on nba.com, I see many completed games ([screenshot](https://imgur.com/APVz9CZ)).  But if I run nba-go with `game -y` it shows those games as not yet started ([screenshot](https://imgur.com/FGHDUWE)).  These games completed ~9-13 hours ago--why isn't the program able to grab the data?  Is there a known delay?

Is this the issue I am meant to be fixing, or is it a separate issue?  To me, it seems like a separate issue.  I don't have a problem debugging it, but I just want to make sure we're on the same page before I proceed.

Thanks!

**Comment by pedromql** [comment] 2017-11-11 18:28
@cagross it seems that you've ran `game -t` on the second screenshot instead of `game -y` as you state.

**Comment by cagross** [comment] 2017-11-11 18:32
Sorry, that was the wrong screenshot.  Here is the [correct screenshot](https://imgur.com/LoaT60E).

**Comment by jhamet93** [comment] 2017-11-12 22:20
@cagross 

If I'm not mistaken, there should be no delay between nba.com and nba-go because they're using the same api to obtain results. The nba-go code just renders the score in the response from the snippets I read so I don't believe this is a related issue

**Comment by cagross** [comment] 2017-11-14 17:43
OK.  During the day I did a little more testing and wasn't able to replicate the issue.  So I guess I'll continue working on resolving my specific issue.

Here is the testing I did.  It is currently now 12:40 AM on 15 November, Thailand time.  Within the past 12 hours I ran game -t and game -y at three different times.  Here are the results (all time stamps are Thailand time):

14 Nov 1:13 PM
game -t showed the games for 14 Nov (first game BOS @ BKY).  nba-go showed none had started yet, as expected.
game -u showed the games for 13 Nov (first game SAC @ WAS).  Those games had all completed, and nba-go showed all completed scores, as expected.

14 Nov 10:40 PM
game -t showed the games for 14 Nov (first game BOS @ BKY).  nba-go showed none had started yet, as expected.
game -y showed the games for 13 Nov (first game SAC @ WAS).  Those games had all completed, and nba-go showed all completed scores, as expected.

15 Nov 12:30 AM
game -t showed the games for 15 Nov (first game SAC @ ATL).  nba-go showed none had started yet, as expected.
game -y showed the games for 14 Nov (first game BOS @ BKY).  nba-go showed none had started yet, as expected.

Also, I should note I am using my local version of nba-go, which has not been synced with the latest master version in ~72 hours.

**Comment by cagross** [comment] 2017-12-20 14:01
Hi.  Are you still interested in a resolution to this issue?  I have some spare time now and can continue working on it if you'd like.

**Closed** 2018-01-24 13:50 UTC

**Comment by aviskarkc10** [comment] 2018-12-29 04:12
This problem is still not solved. I have problems seeing the results of today. I live in Asia and whenever the clock hits 12:00am in LA, I will get tomorrow's fixtures rather than getting to see the results of today even though the game has been played today for my location. 

I propose handling this the way the stats.nba.com website does whenever user gives the `-t` flag.
We can call this endpoint http://data.nba.com/data/v2015/json/mobile_teams/nba/2018/scores/00_todays_scores to get all the results of today.  

I was going to send a PR, but I noticed you use a different package for calling the apis. I can fix this issue, I just wanted to discuss how you would like it to be done?

**Comment by xxhomey19** [comment] 2019-01-15 08:51
Hi @aviskarkc10 
I faced this issue in another project, and here is the [implementation](https://github.com/xxhomey19/nba-bar/blob/master/renderer/utils/getApiDate.js). It works perfectly so far. I might copy that file to here. What do you think?

**Comment by aviskarkc10** [comment] 2019-01-15 08:56
If that works it will be great because the solution I suggested completely deviates from how data is fetched in the application at the current time. Let me test with your implementation and get back to you.
